### PR TITLE
Driverize

### PR DESCRIPTION
**Pull request by morissette**

### CODE REVIEW

**Comment by eversdyk** [comment]
- Have not seen the pip install -e . before, is that because Travis cannot see your requirements.txt file?
- As discussed earlier, really appreciate your adding the minimum .config requirements to the README.
- Since we talked a couple hours ago, it appears you moved most of the contents of the service module into your crossbar module.  I think I see why you did it, it is because these components are specific to crossbar.io, right? and you wanted to abstract them away from the creation of the service class?

**Review by eversdyk — APPROVED** [review]
Have not seen the pip install -e . before, is that because Travis cannot see your requirements.txt file?
As discussed earlier, really appreciate your adding the minimum .config requirements to the README.
Since we talked a couple hours ago, it appears you moved most of the contents of the service module into your crossbar module. I think I see why you did it, it is because these components are specific to crossbar.io, right? and you wanted to abstract them away from the creation of the service class?

**Comment by morissette** [comment]
pip install -e .

Installs a package from local directory. Its normally only used during package development.

See: https://pip.pypa.io/en/stable/reference/pip_install/#editable-installs


Correct; this better supports the driver mechanism so in the future when crossbar limitations are reached; we can seamlessly switch underlying event transport and store mechanism. If you go way back in history you'll see this project initially was built on beanstalkd; then amazon kinesis; both of which can now be drivers.

**Comment by morissette** [comment]
Also with using decorator vs multiple inheritance to add drivers is as simple as implementing the service class on another module that is dynamically imported

**Pull request merged**
